name: storia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  infinite_scroll_pagination: ^3.2.0
  open_filex: ^4.3.2
  freezed_annotation: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  equatable: ^2.0.5
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  build_runner: ^2.3.3
  provider: ^6.0.5
  retrofit_generator: ^8.1.0
  keyboard_dismisser: ^3.0.0
  auto_route: ^8.1.3
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  path_provider: ^2.0.11

  shared_preferences: ^2.1.0
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  get_it: ^7.2.0
  alice: ^0.4.2
  image_picker: ^1.1.2
  basic_utils: ^5.7.0
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.6.1
  cached_network_image: ^3.4.0
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.3.2
  auto_route_generator: ^8.0.0
  json_serializable: ^6.6.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
flutter_intl:
  enabled: true